language: scala
sudo: true
jdk: 
  - oraclejdk8
script:
  - sbt test
before_script:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo chmod +x /usr/local/bin/sbt
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.coursier
    - $HOME/.embedmysql
    - $HOME/.embedpostgresql
deploy:
  provider: releases
  api-key: "a26dbdaf913ef771da747e2d9dfe2aefc8916fb0"
  file_glob: true
  file: target/*
  skip_cleanup: true
  on:
    tags: true
